weather/urls.py
from django.conf.urls import url

from . import views

app_name = 'weather'
urlpatterns = [
    url(r'^$', views.start_page, name='start_page'),
    url(r'^(?P<city_id>[0-9]+)/$', views.index, name='index'),
    url(r'^(?P<city_id>[0-9]+)/api/weather/$', views.give_weather_json, name='get_weather'),
    url(r'^api/city_list/$', views.give_city_json, name='get_city_list'),
]

weather_api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('weather.urls')),
    url(r'^admin/', admin.site.urls),
]

weather/models.py
from django.db import models


class JsonWeather(models.Model):
    weather = models.TextField()
    date_request = models.CharField(max_length=10)

    def __str__(self):
        return str(self.date_request)


class CityList(models.Model):
    city = models.TextField()

weather/views.py
import requests
import datetime
import json

from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.conf import settings

from .models import JsonWeather, CityList


URL = 'http://api.openweathermap.org/data/2.5/forecast/daily?id=703448&cnt=14&units=metric' \
      '&APPID=14ff65b01e70f4669d1efc10fac26a45'


def start_page(requset):
    return redirect('/703448/')


def index(request, city_id):
    if request.method == 'POST':
        if 'list_city' in request.POST:
            update_city_list()
    return render(request, 'weather/index.html')


def change_url(city_id):
    return 'http://api.openweathermap.org/data/2.5/forecast/' \
           'daily?id={}&cnt=14&units=metric&APPID=14ff65b01e70f4669d1efc10fac26a45'.format(city_id)


def parser(url):
    url = url
    response = requests.get(url)
    return response.json()


def save_weather_to_db(url):
    parsing = parser(url)
    jw = JsonWeather(weather=json.dumps(parsing), date_request=str(datetime.date.today()))
    jw.save()


def give_weather_json(request, city_id):
    url = change_url(city_id)
    save_weather_to_db(url)
    jw = JsonWeather.objects.all()
    jw = list(jw)[-1]
    jw = json.loads(jw.weather)
    return HttpResponse(json.dumps(jw))


def give_city_json(request):
    city_list = CityList.objects.all()[0].city
    city_list = json.loads(city_list)
    city_list.sort(key=lambda x: x['name'])
    return HttpResponse(json.dumps(city_list))


def update_city_list():
    CityList.objects.all().delete()
    with open(settings.BASE_DIR+'/weather/media/city.list.json', 'rt') as f:
        i = 0
        list_ad = []
        for js in f.readlines():
            list_ad.append(json.loads(js.rstrip()))
            i += 1
            print(i)
        city_list = CityList(city=json.dumps(list_ad))
        city_list.save()

weather/templates/weather/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>

</head>
<body>

<div id="temperature"></div>
<div id="pressure"></div>

<form method="POST">{% csrf_token %}
    <p><input type="submit" value="Обновить спиок городов" name="list_city"></p>
</form>

<form id="select_city" action="" method="POST">{% csrf_token %}
    <select id="id_city" name="city_id">
        <option value="">Select a city</option>
    </select>
    <input id="city" type="submit">
</form>

<p id="p_city">Город: </p>
<p id="p_coord">Страна: </p>
<table id="table_weather">
    <tr>
        <th>Дата</th>
        <th>Температура<br/>max/min(&#176 C)</th>
        <th>Ветер<br/>(meter/sec)</th>
        <th>Облачность<br/>(%)</th>
        <th>Давление<br/>(hPa)</th>
        <th>Краткое описание</th>
    </tr>
</table>

<script type="text/javascript" src="{% static 'js/index.js' %}"></script>

</body>
</html>